FROM python:2.7.14

RUN apt-get update
RUN apt-get install -y mysql-client-5.5
RUN apt-get install -y ntpdate

RUN mkdir /usr/local/java
RUN mkdir /usr/local/logs
RUN mkdir /usr/local/data
RUN mkdir /usr/local/tmp
RUN mkdir /usr/local/Baymax_Node

#install java
RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jre-8u151-linux-x64.tar.gz
RUN tar -xzvf jre-8u151-linux-x64.tar.gz -C /usr/local/java
RUN rm -rf jre-8u151-linux-x64.tar.gz

ENV JAVA_HOME /usr/local/java/jre1.8.0_151
ENV CLASSPATH $JAVA_HOME/lib
ENV PATH $JAVA_HOME/bin:$PATH


#install redis
RUN wget http://download.redis.io/releases/redis-2.8.24.tar.gz
RUN tar xzf redis-2.8.24.tar.gz
RUN cd redis-2.8.24;make

ENV PATH /redis-2.8.24/src/:$PATH

COPY Doraemon-1.1.8-py2-none-any.whl  /usr/local/tmp/
RUN pip install /usr/local/tmp/Doraemon-1.1.8-py2-none-any.whl

COPY Baymax_Node /usr/local/Baymax_Node/
WORKDIR /usr/local/Baymax_Node/
RUN pip install -r /usr/local/Baymax_Node/requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate